[package]
name = "connui_wgpu"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
connui.workspace = true
image.workspace = true
wgpu.workspace = true

[dev-dependencies]
winit = "0.30"
pollster = "1.0"
connui_widgets.workspace = true

[features]
default = []
