[workspace]
resolver = "2"
default-members = ["connui"]
members = ["connui", "connui_wgpu", "connui_widgets"]

[workspace.package]
version = "0.1.0"
edition = "2024"
# license

[workspace.dependencies]
connui = { path = "connui" }
connui_widgets = { path = "connui_widgets" }

bitflags = "2.13.0"
bytemuck = "1.17.0"
image = "0.25"
msdf_font = "0.3.1"
paste = "1.0.15"
wgpu = "30.0"

# [dev-dependencies]
# ggez = { version = "0.9", default-features = false }
