[package]
name = "connui"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
paste.workspace = true
msdf_font = { workspace = true, features = ["atlas"], optional = true }

[features]
default = ["widgets", "msdf_font"]
msdf_font = ["dep:msdf_font"]
widgets = []
